[package]
name = "slox"
description = "Slow Lox - Part 1 of R. Nystrom's Crafting Interpreters book"
version = "0.1.0"
edition = "2021"

[dependencies]
itertools = "0.10.5"
lazy_static = "1.4.0"

[features]
debug_output = ["dump_tokens", "dump_ast"]
dump_tokens = []
dump_ast = []
